import os
import glob
import re
import json

def parse_all_projects():
    files = sorted(glob.glob('projects/*.md'))
    if not files:
        files = sorted(glob.glob('*.md'))
    files = [f for f in files if os.path.basename(f) != 'README.md']
    
    projects = []
    
    for f in files:
        with open(f, 'r', encoding='utf-8') as fp:
            content = fp.read()
        
        fname = os.path.basename(f)
        # Extract ID
        m_id = re.search(r'^(\d+)', fname)
        pid = int(m_id.group(1)) if m_id else len(projects) + 1
        
        # Title
        m_title = re.search(r'^#\s+(.+)$', content, re.M)
        raw_title = m_title.group(1) if m_title else f
        clean_title = re.sub(r'^Project\s+\d+:\s*', '', raw_title).strip()
        
        # Attributes
        def get_attr(name):
            m = re.search(r'\|\s*\*\*' + name + r'\*\*\s*\|\s*([^|]+)\|', content)
            return m.group(1).strip() if m else ''
        
        category = get_attr('Category')
        algo = get_attr('Algorithm')
        difficulty = get_attr('Difficulty') or 'Beginner'
        dataset = get_attr('Recommended Dataset')
        prereq = get_attr('Prerequisites')
        
        # Sections
        def get_sec(start_pat, end_pat):
            m = re.search(start_pat + r'\n(.*?)(?=' + end_pat + r')', content, re.S)
            return m.group(1).strip() if m else ''
        
        problem = get_sec(r'## 1\.[^\n]*', r'\n---\s*\n|\n## 2')
        theory = get_sec(r'## 2\.[^\n]*', r'\n---\s*\n|\n## 3')
        steps = get_sec(r'## 3\.[^\n]*', r'\n---\s*\n|\n## 4')
        
        # Code block
        m_code = re.search(r'```python\s*\n(.*?)```', content, re.S)
        code = m_code.group(1).strip() if m_code else ''
        
        outputs = get_sec(r'## 5\.[^\n]*', r'\n---\s*\n|\n## 6|\Z')
        challenges = get_sec(r'## 6\.[^\n]*', r'\n---\s*\n|\Z')
        
        # Super category (Harmonized Orange & Amber Palette)
        if pid <= 10:
            track = 'Regression'
            track_num = 1
            color = '#ff8533' # warm tangerine orange
            track_name = 'Supervised Regression'
        elif pid <= 20:
            track = 'Classification'
            track_num = 2
            color = '#ff5500' # electric flame orange
            track_name = 'Supervised Classification'
        elif pid <= 30:
            track = 'Unsupervised'
            track_num = 3
            color = '#ffaa00' # golden glowing amber
            track_name = 'Unsupervised & Anomaly'
        elif pid <= 40:
            track = 'NLP & Text'
            track_num = 4
            color = '#ff7043' # sunset coral orange
            track_name = 'NLP & Text Analytics'
        else:
            track = 'Vision, Recs & RL'
            track_num = 5
            color = '#e64a19' # deep ember vermilion
            track_name = 'Vision, Recs, Series & RL'
            
        projects.append({
            'id': pid,
            'idStr': f'{pid:02d}',
            'filename': fname,
            'title': clean_title,
            'track': track,
            'trackNum': track_num,
            'trackName': track_name,
            'category': category,
            'algorithm': algo,
            'difficulty': difficulty,
            'dataset': dataset,
            'prerequisites': prereq,
            'problem': problem,
            'theory': theory,
            'steps': steps,
            'code': code,
            'outputs': outputs,
            'challenges': challenges,
            'color': color
        })
    
    with open('projects-data.js', 'w', encoding='utf-8') as out:
        out.write('// Autogenerated 50 ML Projects Data\n')
        out.write('window.PROJECTS_DATA = ' + json.dumps(projects, ensure_ascii=False, indent=2) + ';\n')
        
    print(f'Wrote {len(projects)} projects to projects-data.js')

if __name__ == '__main__':
    parse_all_projects()
